run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/jaxxstorm/vers
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - goconst
    - gocyclo
    - gosec
    - dupl
    - gocritic
    - revive
    - exportloopref
  disable:
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gomnd
    - mnd
    - nlreturn
    - paralleltest
    - testpackage
    - wsl
    - varnamelen
    - ireturn
    - tagliatelle

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
        - lll
    - path: examples/
      linters:
        - gosec
        - errcheck
    - path: test_helpers\.go
      linters:
        - gosec
